language: node_js

node_js:
  - "stable"

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: never

script:
  - yarn run lint+build+test
