language: node_js

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: never

node_js:
  - "stable"

script:
  - yarn run lint+build+test
